disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - line_length
  - force_try
  - variable_name
  - function_body_length
  - type_body_length
excluded:
  - xjf-ios-mvvm/Resources
  - Pods
  - fastlane
